# Generated by Django 4.1 on 2022-08-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_receita', models.CharField(max_length=100)),
                ('valor_receita', models.DecimalField(decimal_places=2, max_digits=19)),
                ('data_receita', models.DateField()),
            ],
        ),
    ]
