# Generated by Django 4.1 on 2022-08-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_despesa', models.CharField(max_length=100)),
                ('valor_despesa', models.DecimalField(decimal_places=2, max_digits=19)),
                ('data_despesa', models.DateField()),
            ],
        ),
    ]
